name: Frontend CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend:
    name: Frontend CI AND CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # 根据你的前端所需的Node版本

      - name: Install student frontend dependencies
        run: |
          cd GenshinStart_frontend/vue/student
          npm install

      - name: Install admin frontend dependencies
        run: |
          cd GenshinStart_frontend/vue/admin
          npm install

      - name: Student End Run ESLint
        run: |
          cd GenshinStart_frontend/vue/student
          npm run lint

      - name: Admin End Run ESLint
        run: |
          cd GenshinStart_frontend/vue/admin
          npm run lint
